2.2.10 needs -Wno-error=implicit-function-declaration to build on macOS
* Otherwise:
encoding.c:825:2: error: implicit declaration of function 'rb_str_change_terminator_length' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        rb_str_change_terminator_length(obj, oldtermlen, termlen);
        ^
  and the declaration is indeed missing.
* It's not clear where the -Werror comes from, maybe default of clang on macOS?